### DSTA

Experience: apply NMF to the activity matrix from Ch. 11 of the [MMDS textbook](http://mmds.org/). 

In [1]:
import numpy as np

from sklearn.decomposition import NMF

# constant assigned to the dimension to be introduced by factorization.
K = 2

In [4]:
viewers = ['Joe', 'Jim', 'John', 'Jack', 'Jill', 'Jenny', 'Jane']

films = ['Matrix', 'Alien', 'Star Wars', 'Casablanca', 'Titanic']

ratings =  [[1, 1, 1, 0, 0],
            [3, 3, 3, 0, 0],
            [4, 4, 4, 0, 0],
            [5, 5, 5, 0, 0],
            [0, 0, 0, 4, 4],
            [0, 0, 0, 5, 5],
            [0, 0, 0, 2, 2]]



ratings2 =  [[1, 1, 1, 0, 0],
            [3, 3, 3, 0, 0],
            [4, 4, 4, 0, 0],
            [5, 5, 5, 0, 0],
            [0, 2, 0, 4, 4],
            [0, 0, 0, 5, 5],
            [0, 1, 0, 2, 2]]

In [5]:
# assign as needed
V = np.array(ratings)

In [6]:
# initialization of the Scikit machine
model = NMF(n_components=K, init='random', random_state=0)

W = model.fit_transform(V)

# continuation of the previous call
H = model.components_


In [8]:
print(W)

print(H)

[[3.97051083e-36 8.20375710e-01]
 [0.00000000e+00 2.46112713e+00]
 [1.58820433e-35 3.28150284e+00]
 [0.00000000e+00 4.10187855e+00]
 [1.62445593e+00 0.00000000e+00]
 [2.03056992e+00 0.00000000e+00]
 [8.12227967e-01 0.00000000e+00]]
[[0.         0.         0.         2.46236289 2.46236289]
 [1.21895369 1.21895369 1.21895369 0.         0.        ]]


In [9]:
# let's visualise the error incurred.
print(np.dot(W, H))

# rounding of the result
print(np.rint(np.dot(W, H)))


[[1.00000000e+00 1.00000000e+00 1.00000000e+00 9.77683851e-36
  9.77683851e-36]
 [3.00000000e+00 3.00000000e+00 3.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [4.00000000e+00 4.00000000e+00 4.00000000e+00 3.91073541e-35
  3.91073541e-35]
 [5.00000000e+00 5.00000000e+00 5.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.00000000e+00
  4.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 5.00000000e+00
  5.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e+00
  2.00000000e+00]]
[[1. 1. 1. 0. 0.]
 [3. 3. 3. 0. 0.]
 [4. 4. 4. 0. 0.]
 [5. 5. 5. 0. 0.]
 [0. 0. 0. 4. 4.]
 [0. 0. 0. 5. 5.]
 [0. 0. 0. 2. 2.]]
